Algoritmo "Area do quadrado"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : calcular a area do quadrado
// Autor(a)    : Mariana
// Data atual  : 28/08/2024
Var
// Seção de Declarações das variáveis 
  lado, area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva o lado do quadrado")
leia(lado)
area <- lado*lado
escreval("A area do quadrado é: ", area)

Fimalgoritmo